.PHONY: test
test:
	cd src/api && GOSUMDB=off go test ./...
	cd test/component && GOSUMDB=off go test ./...
	cd test/unit/ui && npm ci && npm test
	cd test/ui && npm ci && npx playwright install chromium && CI=true npm test
